package generator

import (
	"strings"
	"testing"

	"github.com/mailru/activerecord/internal/pkg/arerror"
	"github.com/mailru/activerecord/internal/pkg/ds"
)

func TestGenerateFixture(t *testing.T) {
	type args struct {
		params PkgData
	}

	namespaceNum := int64(2)

	packageName := "gift"

	tests := []struct {
		name    string
		args    args
		want    *arerror.ErrGeneratorPhases
		wantStr map[string][]string
	}{
		{
			name: "simplePkg",
			want: nil,
			args: args{
				params: PkgData{
					ARPkg:      packageName,
					ARPkgTitle: "Gift",
					Indexes: []ds.IndexDeclaration{
						{
							Name:     "Id",
							Num:      0,
							Selector: "SelectById",
							Fields:   []int{0},
							FieldsMap: map[string]ds.IndexField{
								"Id": {IndField: 0, Order: 0},
							},
							Primary: true,
							Unique:  true,
							Type:    "string",
						},
						{
							Name:     "Inv",
							Num:      1,
							Selector: "SelectByInv",
							Fields:   []int{2},
							FieldsMap: map[string]ds.IndexField{
								"Inv": {IndField: 2, Order: 0},
							},
							Primary: false,
							Unique:  false,
							Type:    "bool",
						},
					},
					FieldList: []ds.FieldDeclaration{
						{
							Name:       "Id",
							Format:     "string",
							PrimaryKey: true,
							Mutators:   []ds.FieldMutator{},
							Serializer: []string{},
							ObjectLink: "",
						},
						{
							Name:       "Code",
							Format:     "string",
							Mutators:   []ds.FieldMutator{},
							Serializer: []string{},
							ObjectLink: "",
						},
						{
							Name:       "Inv",
							Format:     "bool",
							Mutators:   []ds.FieldMutator{},
							Serializer: []string{},
							ObjectLink: "",
						},
					},
					FieldObject: map[string]ds.FieldObject{},
					LinkedObject: map[string]ds.RecordPackage{
						packageName: {
							Namespace: ds.NamespaceDeclaration{
								Num:         0,
								PublicName:  "Gift",
								PackageName: "gift",
								ModuleName:  "github.com/foo/bar/baz.git/internal/pkg/model/repository/cmpl/",
							},
						},
					},
					Server:      ds.ServerDeclaration{Timeout: 500, Host: "127.0.0.1", Port: "11011"},
					Container:   ds.NamespaceDeclaration{Num: namespaceNum, PublicName: "Testmodel", PackageName: "testmodel"},
					Serializers: map[string]ds.SerializerDeclaration{},
					Imports: []ds.ImportDeclaration{
						{
							ImportName: "obj",
							Path:       "github.com/foo/bar/baz.git/internal/pkg/model/repository/cmpl/gift",
						},
					},
					Triggers: map[string]ds.TriggerDeclaration{},
					Flags:    map[string]ds.FlagDeclaration{},
				},
			},
			wantStr: map[string][]string{
				"fixture": {
					`Code generated by argen. DO NOT EDIT.`,
					`func GetGiftById(Id string) *gift.Gift`,
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ret, got := generateFixture(tt.args.params)
			if got != tt.want {
				t.Errorf("GenerateFixture() = %v, want %v", got, tt.want)
			}

			for name, strs := range tt.wantStr {
				buff, ex := ret[name]
				if !ex {
					t.Errorf("GenerateFixture() Name %s not generated", name)
					return
				}

				for _, substr := range strs {
					if !strings.Contains(buff.String(), substr) {
						t.Errorf("GenerateFixture() = %v, want %v", buff.String(), substr)
					}
				}
			}
		})
	}
}
